// <auto-generated />
using System;
using Kinova.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kinova.Infrastructure.Migrations
{
    [DbContext(typeof(KinovaDbContext))]
    [Migration("20260911041213_updateReportAndScoreTables")]
    partial class updateReportAndScoreTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kinova.Domain.Entities.Doctors.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors", (string)null);
                });

            modelBuilder.Entity("Kinova.Domain.Entities.Exercises.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyPart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Defaults")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DifficultyLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TargetJoints")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000001"),
                            BodyPart = "Shoulder",
                            Category = "Range of Motion",
                            Defaults = "{\"sets\":3,\"reps\":10,\"holdSeconds\":2}",
                            DifficultyLevel = "Beginner",
                            Instructions = "Raise the arm forward and upward to shoulder height, then slowly lower it back down.",
                            Name = "Shoulder Flexion",
                            TargetJoints = "Glenohumeral Joint",
                            VideoUrl = "https://videos.kinova-health.com/exercises/shoulder-flexion.mp4"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000002"),
                            BodyPart = "Knee",
                            Category = "Strength",
                            Defaults = "{\"sets\":3,\"reps\":12,\"holdSeconds\":3}",
                            DifficultyLevel = "Beginner",
                            Instructions = "While seated, extend the knee until the leg is straight, then slowly return to the starting position.",
                            Name = "Seated Knee Extension",
                            TargetJoints = "Knee Joint",
                            VideoUrl = "https://videos.kinova-health.com/exercises/knee-extension.mp4"
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000003"),
                            BodyPart = "Lower Body",
                            Category = "Functional Strength",
                            Defaults = "{\"sets\":3,\"reps\":15,\"holdSeconds\":0}",
                            DifficultyLevel = "Intermediate",
                            Instructions = "Stand with feet shoulder-width apart, lower the hips back and down, then return to standing.",
                            Name = "Bodyweight Squat",
                            TargetJoints = "Hip, Knee, Ankle",
                            VideoUrl = "https://videos.kinova-health.com/exercises/bodyweight-squat.mp4"
                        });
                });

            modelBuilder.Entity("Kinova.Domain.Entities.JointAngles.JointAngleReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Angle")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("JointName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("RepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RepId", "JointName");

                    b.ToTable("JointAngleReadings", (string)null);
                });

            modelBuilder.Entity("Kinova.Domain.Entities.MovementErrors.MovementError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("BodyPart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DeviationValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("RepId");

                    b.ToTable("MovementErrors", (string)null);
                });

            modelBuilder.Entity("Kinova.Domain.Entities.Patients.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("CarePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("Kinova.Domain.Entities.PlanExerciseItems.PlanExerciseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FrequencyPerWeek")
                        .HasColumnType("int");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Repetitions")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("PlanId", "ExerciseId")
                        .IsUnique();

                    b.ToTable("PlanExercises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000001"),
                            ExerciseId = new Guid("33333333-0000-0000-0000-000000000003"),
                            FrequencyPerWeek = 5,
                            PlanId = new Guid("44444444-0000-0000-0000-000000000001"),
                            Repetitions = 15,
                            Sets = 3
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000002"),
                            ExerciseId = new Guid("33333333-0000-0000-0000-000000000002"),
                            FrequencyPerWeek = 4,
                            PlanId = new Guid("44444444-0000-0000-0000-000000000001"),
                            Repetitions = 12,
                            Sets = 3
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000003"),
                            ExerciseId = new Guid("33333333-0000-0000-0000-000000000002"),
                            FrequencyPerWeek = 3,
                            PlanId = new Guid("44444444-0000-0000-0000-000000000002"),
                            Repetitions = 10,
                            Sets = 2
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000004"),
                            ExerciseId = new Guid("33333333-0000-0000-0000-000000000001"),
                            FrequencyPerWeek = 6,
                            PlanId = new Guid("44444444-0000-0000-0000-000000000003"),
                            Repetitions = 10,
                            Sets = 3
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000005"),
                            ExerciseId = new Guid("33333333-0000-0000-0000-000000000001"),
                            FrequencyPerWeek = 4,
                            PlanId = new Guid("44444444-0000-0000-0000-000000000004"),
                            Repetitions = 8,
                            Sets = 2
                        });
                });

            modelBuilder.Entity("Kinova.Domain.Entities.Plans.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Plans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000001"),
                            Description = "Progressive strengthening plan following ACL reconstruction, weeks 6-12.",
                            DoctorId = new Guid("fe0691d2-30ad-f111-8f74-00155df0670e"),
                            EndDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "ACL Recovery - Phase 2",
                            PatientId = new Guid("643fbb85-2fad-f111-8f74-00155df0670e"),
                            Source = "Doctor",
                            StartDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000002"),
                            Description = "Initial post-op mobility plan, weeks 0-6.",
                            DoctorId = new Guid("fe0691d2-30ad-f111-8f74-00155df0670e"),
                            EndDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "ACL Recovery - Phase 1",
                            PatientId = new Guid("643fbb85-2fad-f111-8f74-00155df0670e"),
                            Source = "Doctor",
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000003"),
                            Description = "Range-of-motion focused plan for rotator cuff recovery.",
                            DoctorId = new Guid("eb420afe-30ad-f111-8f74-00155df0670e"),
                            EndDate = new DateTime(2026, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Shoulder Mobility Restoration",
                            PatientId = new Guid("d1fcede8-2fad-f111-8f74-00155df0670e"),
                            Source = "Doctor",
                            StartDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000004"),
                            Description = "AI-recommended supplementary plan to accelerate shoulder ROM gains.",
                            DoctorId = new Guid("eb420afe-30ad-f111-8f74-00155df0670e"),
                            EndDate = new DateTime(2026, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Adjunct Mobility Boost",
                            PatientId = new Guid("d1fcede8-2fad-f111-8f74-00155df0670e"),
                            Source = "AIRecommendation",
                            StartDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Kinova.Domain.Entities.Reports.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ScoreId")
                        .IsUnique();

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("Kinova.Domain.Entities.Reps.Rep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("RepNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "RepNumber")
                        .IsUnique();

                    b.ToTable("Reps", (string)null);
                });

            modelBuilder.Entity("Kinova.Domain.Entities.Scores.Score", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<decimal>("AccuracyScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InvalidRepetitions")
                        .HasColumnType("int");

                    b.Property<decimal>("OverallScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("RangeOfMotionScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("StabilityScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ValidRepetitions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("Scores", (string)null);
                });

            modelBuilder.Entity("Kinova.Domain.Entities.Sessions.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("CorrectReps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExerciseId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("ExerciseId1");

                    b.HasIndex("ItemId");

                    b.HasIndex("PatientId", "SessionDate")
                        .HasDatabaseName("IX_Sessions_Patient_Date");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("Kinova.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a95e1a8-9032-4a9f-b8fb-0191988f1746"),
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        },
                        new
                        {
                            Id = new Guid("76f67d8a-3b6f-4ae1-b7cf-29789776548b"),
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        });
                });

            modelBuilder.Entity("Kinova.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PatientId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Kinova.Domain.Entities.Doctors.Doctor", b =>
                {
                    b.HasOne("Kinova.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Kinova.Domain.Entities.Doctors.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kinova.Domain.Entities.JointAngles.JointAngleReading", b =>
                {
                    b.HasOne("Kinova.Domain.Entities.Reps.Rep", "Rep")
                        .WithMany("AngleReadings")
                        .HasForeignKey("RepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rep");
                });

            modelBuilder.Entity("Kinova.Domain.Entities.MovementErrors.MovementError", b =>
                {
                    b.HasOne("Kinova.Domain.Entities.Reps.Rep", "Rep")
                        .WithMany("MovementErrors")
                        .HasForeignKey("RepId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Rep");
                });

            modelBuilder.Entity("Kinova.Domain.Entities.Patients.Patient", b =>
                {
                    b.HasOne("Kinova.Domain.Entities.Doctors.Doctor", "Doctor")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kinova.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Kinova.Domain.Entities.Patients.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Kinova.Domain.Entities.PlanExerciseItems.PlanExerciseItem", b =>
                {
                    b.HasOne("Kinova.Domain.Entities.Exercises.Exercise", "Exercise")
                        .WithMany("PlanExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kinova.Domain.Entities.Plans.Plan", "Plan")
                        .WithMany("Exercises")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Kinova.Domain.Entities.Plans.Plan", b =>
                {
                    b.HasOne("Kinova.Domain.Entities.Doctors.Doctor", "Doctor")
                        .WithMany("Plans")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kinova.Domain.Entities.Patients.Patient", "Patient")
                        .WithMany("Plans")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Kinova.Domain.Entities.Reports.Report", b =>
                {
                    b.HasOne("Kinova.Domain.Entities.Doctors.Doctor", "Doctor")
                        .WithMany("Reports")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kinova.Domain.Entities.Patients.Patient", "Patient")
                        .WithMany("Reports")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kinova.Domain.Entities.Scores.Score", "Score")
                        .WithOne()
                        .HasForeignKey("Kinova.Domain.Entities.Reports.Report", "ScoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kinova.Domain.Entities.Sessions.Session", "Session")
                        .WithOne("Report")
                        .HasForeignKey("Kinova.Domain.Entities.Reports.Report", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Score");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Kinova.Domain.Entities.Reps.Rep", b =>
                {
                    b.HasOne("Kinova.Domain.Entities.Sessions.Session", "Session")
                        .WithMany("Reps")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Kinova.Domain.Entities.Scores.Score", b =>
                {
                    b.HasOne("Kinova.Domain.Entities.Sessions.Session", "Session")
                        .WithOne("Score")
                        .HasForeignKey("Kinova.Domain.Entities.Scores.Score", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Kinova.Domain.Entities.Sessions.Session", b =>
                {
                    b.HasOne("Kinova.Domain.Entities.Exercises.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kinova.Domain.Entities.Exercises.Exercise", null)
                        .WithMany("Sessions")
                        .HasForeignKey("ExerciseId1");

                    b.HasOne("Kinova.Domain.Entities.PlanExerciseItems.PlanExerciseItem", "PlanExerciseItem")
                        .WithMany("Sessions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kinova.Domain.Entities.Patients.Patient", "Patient")
                        .WithMany("Sessions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Patient");

                    b.Navigation("PlanExerciseItem");
                });

            modelBuilder.Entity("Kinova.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.HasOne("Kinova.Domain.Entities.Doctors.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("Kinova.Domain.Entities.Patients.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Kinova.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Kinova.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Kinova.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Kinova.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kinova.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Kinova.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kinova.Domain.Entities.Doctors.Doctor", b =>
                {
                    b.Navigation("Patients");

                    b.Navigation("Plans");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Kinova.Domain.Entities.Exercises.Exercise", b =>
                {
                    b.Navigation("PlanExercises");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Kinova.Domain.Entities.Patients.Patient", b =>
                {
                    b.Navigation("Plans");

                    b.Navigation("Reports");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Kinova.Domain.Entities.PlanExerciseItems.PlanExerciseItem", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Kinova.Domain.Entities.Plans.Plan", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("Kinova.Domain.Entities.Reps.Rep", b =>
                {
                    b.Navigation("AngleReadings");

                    b.Navigation("MovementErrors");
                });

            modelBuilder.Entity("Kinova.Domain.Entities.Sessions.Session", b =>
                {
                    b.Navigation("Report");

                    b.Navigation("Reps");

                    b.Navigation("Score");
                });
#pragma warning restore 612, 618
        }
    }
}
